### ISSUE TITLE
0.1 checklist

### ISSUE THREAD

**Issue by fables-tales** [samphippen/descriptor#2]
- [ ] nested example groups
- [ ] before blocks
- [ ] filter examples by description ( `cargo run descriptor -d 'foo'` regex matches any examples that have `foo` in their full description path)
- [x] print failed examples with files and line numbers at end of suite run
- [ ] Code of Conduct
- [ ] update readme with usage docs

**Comment by fables-tales** [comment]
@sgrif: anything else you think should exist here?

**Comment by sgrif** [comment]
Worth relicensing to Apache 2/MIT dual for better interop with the rest of the Rust community
